### ISSUE TITLE
Tidy up the Readme

### ISSUE THREAD

**Issue by nelsonic** [dwyl/goodparts#263]
As a `person` _new_ to this repo/project the `README.md` feels "_unpolished_".
This will 

## Tasks/Todo:

+ [ ] Re-read the readme with [`"shoshin"`](https://en.wikipedia.org/wiki/Shoshin) eyes and
  + [ ] substitute "long" words for more beginner-friendly vocab.
  + [ ] correct any typos in the readme (_editor with good English/grammar skills required!_)
  + [ ] where a technical term is _required_ ensure it is hyperlinked
  + [ ] align all "badges" on a single line for consistency
  + [ ] add instructions for how to include the `goodparts` badge! https://github.com/dwyl/goodparts/issues/253
  + [ ] add some `<br />` space between "main" section of readme and `tldr;` section
  + [ ]  ... anything else that you spot that we can improve. (_please leave a comment in this issue to discuss before making the change, thanks!_)

**Comment by iteles** [comment]
Adding a line specifically around why we've gone with 'no ES6' is probably also worthwhile: https://github.com/dwyl/goodparts/issues/144#issuecomment-258212284 (thanks @eliascodes !)

**Comment by iteles** [comment]
#12 is also relevant here.
